name: yunohost nixops branch

on:
  push:
    branches:
      - master

jobs:
  nixops:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: cachix/install-nix-action@v10
        with:
          nix_path: nixpkgs=https://github.com/NixOS/nixpkgs/archive/master.tar.gz
          skip_adding_nixpkgs_channel: true
      - name: git config
        run: |
          git config user.name actions
          git config user.email "actions@eadwu.flakes"
      - name: generate nixops branch
        run: |
          git revert --no-edit 380467c51f1c2d55030e8655f25cf059a9282921
          git push --force origin HEAD:nixops
